//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_log
    {
        public long log_id { get; set; }
        public Nullable<int> kullanici_id { get; set; }
        public string islem_turu { get; set; }
        public string tablo_adi { get; set; }
        public Nullable<int> kayit_id { get; set; }
        public string eski_deger { get; set; }
        public string yeni_deger { get; set; }
        public Nullable<System.DateTime> islem_tarihi { get; set; }
        public string aciklama { get; set; }
    }
}
