//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class banka_hesaplari
    {
        public int hesap_id { get; set; }
        public int personel_id { get; set; }
        public string banka_adi { get; set; }
        public string iban { get; set; }
        public bool birincil_hesap_mi { get; set; }
    
        public virtual personel personel { get; set; }
    }
}
