//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class duyurular
    {
        public int duyuru_id { get; set; }
        public string baslik { get; set; }
        public string icerik { get; set; }
        public int yayinlayan_id { get; set; }
        public Nullable<System.DateTime> yayin_tarihi { get; set; }
        public Nullable<System.DateTime> gecerlilik_tarihi { get; set; }
    
        public virtual personel personel { get; set; }
    }
}
