//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class egitim_katilimlari
    {
        public int katilim_id { get; set; }
        public int personel_id { get; set; }
        public int egitim_id { get; set; }
        public Nullable<bool> tamamlama_durumu { get; set; }
        public Nullable<int> puan { get; set; }
        public string sertifika_yolu { get; set; }
    
        public virtual sirket_egitimleri sirket_egitimleri { get; set; }
        public virtual personel personel { get; set; }
    }
}
