//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class izinler
    {
        public int izin_id { get; set; }
        public int personel_id { get; set; }
        public int izin_turu_id { get; set; }
        public System.DateTime baslangic_tarihi { get; set; }
        public System.DateTime bitis_tarihi { get; set; }
        public Nullable<decimal> izin_gun_sayisi { get; set; }
        public string aciklama { get; set; }
        public Nullable<System.DateTime> talep_tarihi { get; set; }
        public string onay_durumu { get; set; }
        public Nullable<int> onaylayan_personel_id { get; set; }
    
        public virtual izin_turleri izin_turleri { get; set; }
        public virtual personel personel { get; set; }
        public virtual personel personel1 { get; set; }
    }
}
