//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class maas_gecmisi
    {
        public int maas_id { get; set; }
        public int personel_id { get; set; }
        public decimal brut_maas { get; set; }
        public System.DateTime baslangic_tarihi { get; set; }
        public string degisiklik_nedeni { get; set; }
    
        public virtual personel personel { get; set; }
    }
}
