//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personel()
        {
            this.banka_hesaplari = new HashSet<banka_hesaplari>();
            this.duyurular = new HashSet<duyurular>();
            this.egitim_katilimlari = new HashSet<egitim_katilimlari>();
            this.izinler = new HashSet<izinler>();
            this.izinler1 = new HashSet<izinler>();
            this.maas_gecmisi = new HashSet<maas_gecmisi>();
            this.personel_belgeleri = new HashSet<personel_belgeleri>();
            this.personel_vardiyalari = new HashSet<personel_vardiyalari>();
            this.personel1 = new HashSet<personel>();
            this.zimmet = new HashSet<zimmet>();
        }
    
        public int personel_id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string tc_kimlik_no { get; set; }
        public string sgk_sicil_no { get; set; }
        public string personel_sicil_no { get; set; }
        public System.DateTime dogum_tarihi { get; set; }
        public string cinsiyet { get; set; }
        public string medeni_durum { get; set; }
        public string telefon_kisisel { get; set; }
        public string eposta_is { get; set; }
        public string eposta_kisisel { get; set; }
        public string adres { get; set; }
        public System.DateTime ise_giris_tarihi { get; set; }
        public Nullable<System.DateTime> isten_ayrilma_tarihi { get; set; }
        public bool aktif_mi { get; set; }
        public string calisma_sekli { get; set; }
        public string fotograf_yolu { get; set; }
        public Nullable<int> departman_id { get; set; }
        public Nullable<int> unvan_id { get; set; }
        public Nullable<int> yonetici_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<banka_hesaplari> banka_hesaplari { get; set; }
        public virtual departmanlar departmanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<duyurular> duyurular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<egitim_katilimlari> egitim_katilimlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<izinler> izinler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<izinler> izinler1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<maas_gecmisi> maas_gecmisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personel_belgeleri> personel_belgeleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personel_vardiyalari> personel_vardiyalari { get; set; }
        public virtual unvanlar unvanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personel> personel1 { get; set; }
        public virtual personel personel2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zimmet> zimmet { get; set; }
    }
}
