//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel_vardiyalari
    {
        public int personel_vardiya_id { get; set; }
        public int personel_id { get; set; }
        public int vardiya_id { get; set; }
        public System.DateTime baslangic_tarihi { get; set; }
        public System.DateTime bitis_tarihi { get; set; }
    
        public virtual personel personel { get; set; }
        public virtual vardiya_tanimlari vardiya_tanimlari { get; set; }
    }
}
