//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel_belgeleri
    {
        public int belge_id { get; set; }
        public int personel_id { get; set; }
        public int belge_turu_id { get; set; }
        public string belge_adi { get; set; }
        public Nullable<System.DateTime> yuklenme_tarihi { get; set; }
        public string dosya_yolu { get; set; }
    
        public virtual belge_turleri belge_turleri { get; set; }
        public virtual personel personel { get; set; }
    }
}
