//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class sirket_egitimleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sirket_egitimleri()
        {
            this.egitim_katilimlari = new HashSet<egitim_katilimlari>();
        }
    
        public int egitim_id { get; set; }
        public string egitim_adi { get; set; }
        public string egitmen { get; set; }
        public Nullable<System.DateTime> baslangic_tarihi { get; set; }
        public Nullable<System.DateTime> bitis_tarihi { get; set; }
        public string konum { get; set; }
        public string aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<egitim_katilimlari> egitim_katilimlari { get; set; }
    }
}
