//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class zimmet
    {
        public int zimmet_id { get; set; }
        public int personel_id { get; set; }
        public string urun_adi { get; set; }
        public string seri_numarasi { get; set; }
        public System.DateTime verilis_tarihi { get; set; }
        public Nullable<System.DateTime> iade_tarihi { get; set; }
        public string aciklama { get; set; }
    
        public virtual personel personel { get; set; }
    }
}
